BookingTour/Models/PaymentConfirmationViewModel.cs
namespace BookingTour.Models
{
    public class PaymentConfirmationViewModel
    {
        public long IdInvoice { get; set; }
        public decimal? TotalAmount { get; set; }
        public DateTime BillingDate { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsRefunded { get; set; }
    }
}

BookingTour/Models/Tour.cs
using System;
using System.Collections.Generic;

namespace BookingTour.Models;

public partial class Tour
{
    public long IdTour { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Image { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public long? MaxQuantity { get; set; }

    public decimal? Price { get; set; }

    public string? IsDelete { get; set; }

    public long IdType { get; set; }

    public long IdTrans { get; set; }

    public long IdHotel { get; set; }

    public string? ApprovalStatus { get; set; }

    public string? IdUser { get; set; }

    public virtual Hotel? IdHotelNavigation { get; set; }

    public virtual Transportation? IdTransNavigation { get; set; }

    public virtual TypeOfTour? IdTypeNavigation { get; set; }
     

    public virtual ICollection<Image> images { get; set; } = new List<Image>();
    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
    public virtual ICollection<Booking> Booking { get; set; } = new List<Booking>();


    public virtual ICollection<UsersFavoriteTour> UsersFavoriteTours { get; set; } = new List<UsersFavoriteTour>();
    public virtual ICollection<TourDetail> TourDetails { get; set; } = new List<TourDetail>();
    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
    public virtual AspNetUser? IdUserNavigation { get; set; }

}

BookingTour/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingTour.Data;
using BookingTour.Models;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;
using X.PagedList.Mvc.Core;
using X.PagedList;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Localization;
using BookingTour.Resources;
using Microsoft.AspNetCore.Identity;
namespace BookingTour.Controllers
{
    public class ToursController : Controller
    {
        private readonly YourExistingDbContextName _context;
        private readonly AppDbContext _context1;
		private readonly IStringLocalizer<Resource> _localizer;
		private readonly UserManager<ApplicationUser> _userManager;
		public ToursController(YourExistingDbContextName context, AppDbContext context1, IStringLocalizer<Resource> localizer, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _context1 = context1;
            _localizer = localizer;
			_userManager = userManager;
		}

        // GET: Tours
        public async Task<IActionResult> Index(int? page)
        {

            var toursQuery = _context.Tours
                .Include(t => t.IdHotelNavigation)
                .Include(t => t.IdTransNavigation)
                .Include(t => t.IdTypeNavigation)
                .Where(t => t.ApprovalStatus == "Đã phê duyệt" && t.IsDelete == "N");

            // Phân trang
            int pageSize = 10; // Số lượng item trên mỗi trang
            int pageNumber = (page ?? 1); // Nếu page null thì mặc định là trang 1

            // Tính toán số lượng tour từ dữ liệu
            var totalTours = await toursQuery.CountAsync();

            // Lấy các tour trong phạm vi trang hiện tại
            var tours = await toursQuery
                .Skip((pageNumber - 1) * pageSize) // Bỏ qua số lượng bản ghi của các trang trước
                .Take(pageSize) // Lấy số lượng bản ghi của trang hiện tại
                .ToListAsync();

            // Lấy các tour phổ biến
            ViewBag.PopularTours = await _context.Tours
                .Include(t => t.IdHotelNavigation)
                .Include(t => t.IdTransNavigation)
                .Include(t => t.IdTypeNavigation)
                .Where(t => t.ApprovalStatus == "Đã phê duyệt" && t.IsDelete == "N")
                .OrderByDescending(t => t.Price)
                //.Take(4)
                .ToListAsync();

            // Lấy các tour được đặt nhiều nhất
            ViewBag.MostBookedTours = await _context.Bookings
                .Where(b => b.IdTourNavigation.ApprovalStatus == "Đã phê duyệt" && b.IdTourNavigation.IsDelete == "N")
                .GroupBy(b => b.IdTour)
                .OrderByDescending(g => g.Count())
                .Take(5)
                .Select(g => new
                {
                    Tour = g.FirstOrDefault().IdTourNavigation,
                    BookingCount = g.Count()
                })
                .ToListAsync();

            // Thêm thông tin phân trang vào ViewBag
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalTours / pageSize); // Tính tổng số trang
            ViewBag.CurrentPage = pageNumber;
            ViewBag.HasPreviousPage = pageNumber > 1;
            ViewBag.HasNextPage = pageNumber < ViewBag.TotalPages;

            var viewModel = new SearchTourViewModel
            {
                Tours = tours, // Dữ liệu tours đã phân trang
                Destinations = await _context.Destinations.ToListAsync(),
                TourTypes = await _context.TypeOfTours.ToListAsync()
            };

            return View(viewModel);
        }

        public async Task<IActionResult> TourList(int? page, long? typeId, decimal? maxPrice, string hotelName, string transportationName, string typeName, string priceOrder)
        {
            // Lấy danh sách các tour đã được phê duyệt và chưa bị xóa
            var toursQuery = _context.Tours
                .Include(t => t.IdHotelNavigation)
                .Include(t => t.IdTransNavigation)
                .Include(t => t.IdTypeNavigation)
                .Where(t => t.ApprovalStatus == "Đã phê duyệt" && t.IsDelete == "N");

            // Lọc theo loại tour nếu typeId được cung cấp
            if (typeId.HasValue)
            {
                toursQuery = toursQuery.Where(t => t.IdType == typeId.Value);
            }

            // Lọc theo giá tối đa nếu maxPrice được cung cấp
            if (maxPrice.HasValue)
            {
                toursQuery = toursQuery.Where(t => t.Price <= maxPrice.Value);
            }

            // Lọc theo tên khách sạn nếu hotelName được cung cấp
            if (!string.IsNullOrEmpty(hotelName))
            {
                toursQuery = toursQuery.Where(t => t.IdHotelNavigation.Name.Contains(hotelName));
            }

            // Lọc theo tên phương tiện nếu transportationName được cung cấp
            if (!string.IsNullOrEmpty(transportationName))
            {
                toursQuery = toursQuery.Where(t => t.IdTransNavigation.Name.Contains(transportationName));
            }

            // Lọc theo tên loại tour nếu typeName được cung cấp
            if (!string.IsNullOrEmpty(typeName))
            {
                toursQuery = toursQuery.Where(t => t.IdTypeNavigation.Name.Contains(typeName));
            }
            if (priceOrder == "asc")
            {
                toursQuery = toursQuery.OrderBy(t => t.Price);
            }
            else if (priceOrder == "desc")
            {
                toursQuery = toursQuery.OrderByDescending(t => t.Price);
            }
            // Phân trang
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var totalTours = await toursQuery.CountAsync();
            var tours = await toursQuery
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            // Thêm thông tin phân trang vào ViewBag
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalTours / pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.HasPreviousPage = pageNumber > 1;
            ViewBag.HasNextPage = pageNumber < ViewBag.TotalPages;

            var viewModel = new SearchTourViewModel
            {
                Tours = tours,
                Destinations = await _context.Destinations.ToListAsync(),
                TourTypes = await _context.TypeOfTours.ToListAsync() // Lấy danh sách TypeOfTour để hiển thị
            };

            return View(viewModel);
        }




        // GET: Tours/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tour = await _context.Tours
                .Include(t => t.IdHotelNavigation)
                .Include(t => t.IdTransNavigation)
                .Include(t => t.IdTypeNavigation)
         
                .Include(t => t.Comments)
                .Include(t => t.UsersFavoriteTours)
                      .Include(t => t.UsersFavoriteTours.Where(c => c.IdTour == id))
                //.Include(t => t.Reports)
                //.Include(t => t.Reports.Where(c => c.IdTour == id))
                .ThenInclude(c => c.IdNavigation)
                .Include(t => t.Comments.Where(c => c.IdTour == id))
                .FirstOrDefaultAsync(m => m.IdTour == id );

            if (tour == null)
            {
                return NotFound();
            }
            var averageRating = tour.Comments.Any() ? tour.Comments.Average(c => c.Rating) : 0;
         
            // Truyền giá trị vào ViewBag
            ViewBag.AvgRating = averageRating;
            var images = await _context1.Images.Where(i => i.IdTour == tour.IdTour).ToListAsync();
            tour.images = images;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var comment = await _context.Comments
                .Include(t => t.IdTourNavigation)
                .Include(t => t.IdNavigation)
                .FirstOrDefaultAsync(m => m.IdTour == id);
              ViewBag.UserId = userId;
            var favorite = _context.UsersFavoriteTours.FirstOrDefault(f => f.IdTour == id && f.Id == userId);
            var isFavorited = favorite != null;
            ViewBag.IsFavorited = isFavorited;
            var invoice = await _context.Invoices.FirstOrDefaultAsync(i => i.IdInvoice == id); // Thay thế `TourId` bằng tên thuộc tính chính xác

            if (invoice == null)
            {
                // Nếu chưa có hóa đơn, bạn có thể tạo một hóa đơn mới ở đây nếu cần
                // Hoặc chỉ cần trả về thông báo rằng hóa đơn chưa được tạo
                ViewBag.InvoiceId = null; // Hoặc tạo hóa đơn mới
            }
            else
            {
                ViewBag.InvoiceId = invoice.IdInvoice; // Gán Id hóa đơn vào ViewBag
            }

            ViewBag.Tour = tour;
            return View(tour);
        }


        // GET: Tours/Create
        public IActionResult Create(long tourId)
        {
            var tour = _context.Tours.Find(tourId);
            var booking = _context.Bookings.Find(tourId);
            if (tour == null)
            {
                return NotFound();
            }

            ViewBag.Tour = tour;
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(long tourId, int quantity, [Bind("IdBooking,CheckInDate,CheckOutDate,BookingTime,Id,IdHotel,IdTour,IdStatus")] Booking booking1, decimal totalPrice)
        {
            

            var tour = await _context.Tours.FindAsync(tourId);
            if (tour == null)
            {

BookingTour/Views/Tours/Create.cshtml
@model BookingTour.Models.Tour

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Tour</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdTour" class="control-label"></label>
                <input asp-for="IdTour" class="form-control" />
                <span asp-validation-for="IdTour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxQuantity" class="control-label"></label>
                <input asp-for="MaxQuantity" class="form-control" />
                <span asp-validation-for="MaxQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsDelete" class="control-label"></label>
                <input asp-for="IsDelete" class="form-control" />
                <span asp-validation-for="IsDelete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdType" class="control-label"></label>
                <select asp-for="IdType" class ="form-control" asp-items="ViewBag.IdType"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdTrans" class="control-label"></label>
                <select asp-for="IdTrans" class ="form-control" asp-items="ViewBag.IdTrans"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdHotel" class="control-label"></label>
                <select asp-for="IdHotel" class ="form-control" asp-items="ViewBag.IdHotel"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApprovalStatus" class="control-label"></label>
                <input asp-for="ApprovalStatus" class="form-control" />
                <span asp-validation-for="ApprovalStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookingTour/Views/Tours/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}
@{
    int currentPage = ViewBag.CurrentPage;
    int totalPages = ViewBag.TotalPages;
    bool hasPreviousPage = ViewBag.HasPreviousPage;
    bool hasNextPage = ViewBag.HasNextPage;
}
@using BookingTour.Resources
@using Microsoft.Extensions.Localization
@{
    languageviewmodel languageviewmodel = new languageviewmodel();
}
@inject IStringLocalizer<Resource> _localizer;
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="favicon.png">

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap4" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Source+Serif+Pro:wght@400;700&display=swap" rel="stylesheet">
    <link href="~/css/chat-user.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/daterangepicker.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link href="~/css/user/stylehistory.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
  
</head>
<div class="untree_co-section">
    <div class="container">
        <div class="row text-center justify-content-center mb-5">
            <div class="col-lg-7">
                <h2 class="section-title text-center">@_localizer["Điểm đến phổ biến"]</h2>
            </div>
        </div>

        <div class="owl-carousel owl-3-slider owl-loaded owl-drag">
            @if (ViewBag.MostBookedTours != null)
            {
                @foreach (var tourInfo in ViewBag.MostBookedTours)
                {
                    <div class="item">
                        <a class="media-thumb" href="@tourInfo.Tour.Image" data-fancybox="gallery">
                            <div class="media-text">
                                <h3>@tourInfo.Tour.Name</h3>
                                <span class="location">@_localizer["Số lượt đặt"]: @tourInfo.BookingCount</span>
                            </div>
                            <img src="@Url.Content("~/images/" + @tourInfo.Tour.Image)" alt="@tourInfo.Tour.Name" style="width: 100%; height: 450px; object-fit: cover; " class="img-fluid">
                        </a>
                    </div>
                }
            }
        </div>
    </div>
</div>

<div class="untree_co-section">
    <div class="container">
        <div class="row justify-content-center text-center mb-5">
            <div class="col-lg-6">
                <h2 class="section-title text-center mb-3">@_localizer["Khuyến mãi & Giảm giá đặc biệt"]</h2>
                <p>@_localizer["Tour khám phá thiên nhiên và văn hóa địa phương sẽ đưa bạn đến những vùng đất hoang sơ, nơi bạn có thể tận hưởng vẻ đẹp tuyệt vời của rừng xanh, thác nước hùng vĩ và không khí trong lành. Ngoài việc tham quan các địa danh nổi tiếng, bạn còn có cơ hội tìm hiểu về văn hóa đặc sắc của người dân nơi đây qua các hoạt động truyền thống, ẩm thực độc đáo và những câu chuyện lịch sử thú vị. Đây sẽ là một hành trình đầy cảm hứng, giúp bạn thư giãn và khám phá những điều mới mẻ."]</p>
            </div>
        </div>
        <div class="row">
            @foreach (var tour in ViewBag.PopularTours)
            {
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 mb-4">
                    <div style="border: 1px solid #ddd; border-radius: 10px; padding: 10px; background-color: #fff; min-height: 320px; display: flex; flex-direction: column; justify-content: space-between;">
                        <a href="@Url.Action("Details", "Tours", new { id = tour.IdTour })" class="d-block mb-3">
                            <img src="@Url.Content("~/images/" + tour.Image)"
                                 alt="Hình ảnh"
                                 style="width: 100%; height: 150px; object-fit: cover; border-radius: 5px;">
                        </a>
                        <span class="d-flex align-items-center loc mb-2"
                              style="font-size: 14px; color: #888;">
                            <span class="icon-room mr-3"></span>
                            <span>@tour.IdHotelNavigation?.Name</span>
                        </span>
                        <div style="flex: 1;">
                            <h3 style="font-size: 16px; font-weight: 600; margin-bottom: 5px; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; max-height: 3rem;">
                                <a href="@Url.Action("Details", "Tours", new { id = tour.IdTour })"
                                   style="color: #333; text-decoration: none;">
                                    @tour.Name
                                </a>
                            </h3>
                            <div style="font-size: 14px; font-weight: 500; color: #007bff;">
                                <span>@tour.Price.ToString("C") VNĐ</span>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

        <div class="pagination justify-content-center">
            @if (ViewBag.HasPreviousPage)
            {
                <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            }
            @for (int i = 1; i <= ViewBag.TotalPages; i++)
            {
                <a class="page-link @(i == ViewBag.CurrentPage ? "active" : "")" href="@Url.Action("Index", new { page = i })" style="color: @(i == ViewBag.CurrentPage ? "blue" : "black");">@i</a>
            }
            @if (ViewBag.HasNextPage)
            {
                <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            }
        </div>


      
    </div>
@*     <div class="chat" onclick="toggleChat()">
        <span style="color: white;">Chat</span>  <!-- Nút chat -->
    </div>
    <div id="chatWindow" class="chat-window">
        <div class="chat-header">
            <span>Chat with Admin</span>
            <button onclick="toggleChat()" class="close-btn">×</button>
        </div>
        <div class="chat-body">
            <ul id="messagesList"></ul>
        </div>
        <div class="chat-footer">
            <input id="messageInput" type="text" placeholder="Enter your message" />
            <button id="sendButton" onclick="sendMessage()">Send</button>
        </div>
    </div>
</div> *@


<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.9/signalr.min.js"></script>
<script src="~/js/chat-realtime-user.js"></script>
<script src="~/js/jquery-3.4.1.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/jquery.animateNumber.min.js"></script>
<script src="~/js/jquery.waypoints.min.js"></script>
<script src="~/js/jquery.fancybox.min.js"></script>
<script src="~/js/aos.js"></script>
<script src="~/js/moment.min.js"></script>
<script src="~/js/daterangepicker.js"></script>

<script src="~/js/typed.js"></script>
<script>
        function showPopup(message) {
            const popup = document.getElementById("customPopup");
            const popupMessage = document.getElementById("popupMessage");
            popupMessage.innerText = message; // Gán thông báo động
            popup.classList.remove("hidden"); // Hiển thị popup
        }

        // Hàm đóng popup
        function closePopup() {
            const popup = document.getElementById("customPopup");
            popup.classList.add("hidden"); // Ẩn popup
        }
</script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const successMessage = "@TempData["SuccessMessage"]";
            const errorMessage = "@TempData["ErrorMessage"]";

            if (successMessage) {
                Swal.fire({
                    icon: 'success',
                    title: 'Thành công!',
                    text: successMessage,
                    confirmButtonText: 'OK'
                });
            }

            if (errorMessage) {
                Swal.fire({
                    icon: 'error',
                    title: 'Lỗi!',
                    text: errorMessage,
                    confirmButtonText: 'OK'
                });
            }
        });

    </script>

    <script>
        $(function () {
            var slides = $('.slides'),
                images = slides.find('img');

            images.each(function (i) {
                $(this).attr('data-id', i + 1);
            })

            var typed = new Typed('.typed-words', {
                strings: ["Đà lạt.", " Huế.", " Hà Nội.", " Đà Nẵng.", " Bến Tre."],
                typeSpeed: 80,
                backSpeed: 80,
                backDelay: 4000,
                startDelay: 1000,
                loop: true,
                showCursor: true,
                preStringTyped: (arrayPos, self) => {
                    arrayPos++;
                    console.log(arrayPos);
                    $('.slides img').removeClass('active');
                    $('.slides img[data-id="' + arrayPos + '"]').addClass('active');
                }

            });
        })
    </script>

<script src="~/js/custom.js"></script>


</html>

BookingTour/Views/Tours/PaymentConfirmation.cshtml
@model BookingTour.Models.PaymentConfirmationViewModel

@{
    ViewData["Title"] = "Xác Nhận Thanh Toán";
    Layout = null;
}

@* <h1>Xác Nhận Thanh Toán</h1>

<div class="payment-confirmation">
    <h2>Thông Tin Hóa Đơn</h2>
    <p><strong>ID Hóa Đơn:</strong> @Model.IdInvoice</p>
    <p><strong>Mô Tả:</strong> @Model.Description</p>
    <p><strong>Tổng Số Tiền:</strong> @Model.TotalAmount.ToString("C")</p>
    <p><strong>Ngày Thanh Toán:</strong> @Model.BillingDate.ToString("dd/MM/yyyy")</p>
    <p><strong>Ngày Tạo:</strong> @Model.CreatedAt.ToString("dd/MM/yyyy")</p>

    <div class="payment-status">
        <h3>Trạng Thái Thanh Toán:</h3>
        <p>@(Model.IsRefunded ? "Đã Hoàn Tiền" : "Chưa Hoàn Tiền")</p>
    </div>

    <a asp-controller="Tours" asp-action="Index" class="btn btn-primary">Trở Về Danh Sách Tour</a>
</div>
 *@